### ISSUE TITLE
furigana

### ISSUE THREAD

**Issue by pepakun** [petlyh/JS-Dict#5]
![Screenshot_20231031-094017](https://github.com/petlyh/JS-Dict/assets/138199701/6679ee89-a41a-4616-9ae4-b975317c4fd3)
some furiganas are displayed furiously, amamihanasakigaeru for example

**Comment by petlyh** [comment]
Damn, I thought I had fixed all of the furigana problems by now. Thank you for your report!

**Comment by petlyh** [comment]
Fixed in release v1.0.3 :-)

<img width="400" src="https://github.com/petlyh/JS-Dict/assets/88139840/3e756518-affd-4aea-a676-2e2c0e76fd13">

**Comment by pepakun** [comment]
jᷚoͦbͦ👍ͩ
